sudo: required
services:
  - docker

before_install:
  - docker build -t hemanth318/multidocker -f ./client/Dockerfile.dev ./client

script:
  - docker run =e CI=true hemanth318/multidocker npm test -- --coverage
language: generic

after_success:
  - docker build -t hemanth318/multiclient ./client
  - docker build -t hemanth318/multinginx ./nginx
  - docker build -t hemanth318/multiservice ./server
  - docker build -t hemanth318/multiworker ./worker

# Login to the Docker CLI
- echo "$DOCKER_PWD" | docker login -u "$DOCKER_USERID" --password-stdin

# Push images to Docker Hub
  - docker push hemanth318/multiclient
  - docker push hemanth318/multiserver
  - docker push hemanth318/multinginx
  - docker push hemanth318/multiworker
